package sqlite

import("context";"database/sql";"encoding/json";"fmt";"time";"github.com/ynw0/airgap-mirror/internal/domain";"github.com/ynw0/airgap-mirror/internal/ports")
type ClientStore struct{DB *sql.DB};func NewClientStore(db *sql.DB)*ClientStore{return &ClientStore{DB:db}}
func(c *ClientStore)Begin(ctx context.Context,e domain.Epoch,cid string)error{_,x:=c.DB.ExecContext(ctx,`INSERT INTO download_epochs(id,capsule_id,source_id,base_cursor_kind,base_cursor_value,target_cursor_kind,target_cursor_value,status,total_bytes,total_objects,total_batches,publish_unit_count,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,e.ID,cid,e.SourceID,e.BaseCursor.Kind,e.BaseCursor.Value,e.TargetCursor.Kind,e.TargetCursor.Value,e.Status,e.TotalBytes,e.TotalObjects,e.TotalBatches,e.PublishUnitCount,tstr(e.CreatedAt));return x}
func(c *ClientStore)PutPublishUnit(ctx context.Context,u domain.PublishUnit)error{_,e:=c.DB.ExecContext(ctx,`INSERT INTO planned_publish_units(id,epoch_id,source_id,unit_key,required_count,metadata_path) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET required_count=excluded.required_count,metadata_path=excluded.metadata_path`,u.ID,u.EpochID,u.SourceID,u.Key,u.Required,u.MetadataPath);return e}
func(c *ClientStore)PutArtifact(ctx context.Context,a domain.Artifact)error{_,e:=c.DB.ExecContext(ctx,`INSERT INTO planned_artifacts(id,epoch_id,source_id,logical_path,size,sha256,upstream_url,upstream_integrity,operation,publish_unit_id,package_key,version,metadata,attributes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,a.ID,a.EpochID,a.SourceID,a.LogicalPath,a.Size,a.SHA256,a.UpstreamURL,a.UpstreamIntegrity,a.Operation,a.PublishUnitID,a.PackageKey,a.Version,a.Metadata,[]byte(a.Attributes));return e}
func(c *ClientStore)Commit(ctx context.Context,p domain.EpochPlan)error{_,e:=c.DB.ExecContext(ctx,`UPDATE download_epochs SET target_cursor_kind=?,target_cursor_value=?,status=?,total_bytes=?,total_objects=?,total_batches=?,publish_unit_count=? WHERE id=?`,p.Epoch.TargetCursor.Kind,p.Epoch.TargetCursor.Value,p.Epoch.Status,p.Epoch.TotalBytes,p.Epoch.TotalObjects,p.Epoch.TotalBatches,p.PublishUnitCount,p.Epoch.ID);return e}
func(c *ClientStore)Abort(ctx context.Context,id string,cause error)error{_,e:=c.DB.ExecContext(ctx,`UPDATE download_epochs SET status=?,error_text=? WHERE id=?`,domain.EpochFailed,cause.Error(),id);return e}
func(c *ClientStore)ListUnassignedArtifacts(ctx context.Context,eid string,after int64,limit int)([]ports.PlannedArtifact,error){rows,e:=c.DB.QueryContext(ctx,`SELECT ordinal,id,source_id,logical_path,size,sha256,upstream_url,upstream_integrity,operation,publish_unit_id,package_key,version,metadata,attributes,batch_id,pack_id FROM planned_artifacts WHERE epoch_id=? AND batch_id='' AND ordinal>? ORDER BY ordinal LIMIT ?`,eid,after,limit);if e!=nil{return nil,e};defer rows.Close();var out []ports.PlannedArtifact;for rows.Next(){var p ports.PlannedArtifact;var a domain.Artifact;var op string;var attr []byte;if e=rows.Scan(&p.Ordinal,&a.ID,&a.SourceID,&a.LogicalPath,&a.Size,&a.SHA256,&a.UpstreamURL,&a.UpstreamIntegrity,&op,&a.PublishUnitID,&a.PackageKey,&a.Version,&a.Metadata,&attr,&p.BatchID,&p.PackID);e!=nil{return nil,e};a.EpochID=eid;a.Operation=domain.ArtifactOperation(op);a.Attributes=attr;p.Artifact=a;out=append(out,p)};return out,rows.Err()}
func(c *ClientStore)AssignArtifact(ctx context.Context,id,bid,pid string)error{_,e:=c.DB.ExecContext(ctx,`UPDATE planned_artifacts SET batch_id=?,pack_id=? WHERE id=? AND batch_id=''`,bid,pid,id);return e}
func(c *ClientStore)SetArtifactPackLocation(ctx context.Context,id string,l domain.PackLocation)error{_,e:=c.DB.ExecContext(ctx,`UPDATE planned_artifacts SET pack_id=?,pack_offset=?,record_length=? WHERE id=?`,l.PackID,l.Offset,l.RecordLength,id);return e}
func(c *ClientStore)FinalizeArtifact(ctx context.Context,id string,size int64,sha string)error{tx,e:=c.DB.BeginTx(ctx,nil);if e!=nil{return e};defer tx.Rollback();var os int64;var oh string;if e=tx.QueryRowContext(ctx,`SELECT size,sha256 FROM planned_artifacts WHERE id=?`,id).Scan(&os,&oh);e!=nil{return e};if os!=size||oh!=""&&oh!=sha{return fmt.Errorf("artifact immutable data changed: %w",domain.ErrConflict)};if _,e=tx.ExecContext(ctx,`UPDATE planned_artifacts SET sha256=? WHERE id=?`,sha,id);e!=nil{return e};return tx.Commit()}
func(c *ClientStore)CreateBatch(ctx context.Context,b domain.Batch)error{_,e:=c.DB.ExecContext(ctx,`INSERT INTO download_batches(id,epoch_id,source_id,sequence,status,planned_bytes,object_count,pack_count,created_at) VALUES(?,?,?,?,?,?,?,?,?)`,b.ID,b.EpochID,b.SourceID,b.Sequence,b.Status,b.PlannedBytes,b.ObjectCount,b.PackCount,tstr(b.CreatedAt));return e}
func(c *ClientStore)UpdateBatch(ctx context.Context,b domain.Batch)error{_,e:=c.DB.ExecContext(ctx,`UPDATE download_batches SET status=?,planned_bytes=?,object_count=?,pack_count=? WHERE id=?`,b.Status,b.PlannedBytes,b.ObjectCount,b.PackCount,b.ID);return e}
func(c *ClientStore)CreatePack(ctx context.Context,p domain.Pack)error{_,e:=c.DB.ExecContext(ctx,`INSERT INTO download_packs(id,epoch_id,batch_id,sequence,size,sha256,entry_count,file_path,status) VALUES(?,?,?,?,?,?,?,?,?)`,p.ID,p.EpochID,p.BatchID,p.Sequence,p.Size,p.SHA256,p.EntryCount,p.FilePath,p.Status);return e}
func(c *ClientStore)UpdatePack(ctx context.Context,p domain.Pack)error{_,e:=c.DB.ExecContext(ctx,`UPDATE download_packs SET size=?,sha256=?,entry_count=?,file_path=?,status=? WHERE id=?`,p.Size,p.SHA256,p.EntryCount,p.FilePath,p.Status,p.ID);return e}
func(c *ClientStore)AddDownloadEntry(ctx context.Context,a domain.Artifact,bid,pid string)error{_,e:=c.DB.ExecContext(ctx,`INSERT INTO download_entries(artifact_id,batch_id,pack_id,status,downloaded) VALUES(?,?,?,?,0)`,a.ID,bid,pid,domain.DownloadPending);return e}
func(c *ClientStore)EntryState(ctx context.Context,id string)(domain.DownloadEntryProgress,error){var v domain.DownloadEntryProgress;e:=c.DB.QueryRowContext(ctx,`SELECT artifact_id,status,downloaded,etag,last_modified,error_text FROM download_entries WHERE artifact_id=?`,id).Scan(&v.EntryID,&v.Status,&v.Downloaded,&v.ETag,&v.LastModified,&v.ErrorText);if e!=nil{return v,asNotFound(e)};return v,nil}
func(c *ClientStore)MarkEntryState(ctx context.Context,v domain.DownloadEntryProgress)error{_,e:=c.DB.ExecContext(ctx,`UPDATE download_entries SET status=?,downloaded=?,etag=?,last_modified=?,error_text=? WHERE artifact_id=?`,v.Status,v.Downloaded,v.ETag,v.LastModified,v.ErrorText,v.EntryID);return e}
func(c *ClientStore)Reset(ctx context.Context,ns string)error{_,e:=c.DB.ExecContext(ctx,`DELETE FROM workset_keys WHERE namespace=?`,ns);return e}
func(c *ClientStore)Add(ctx context.Context,ns,key string)(bool,error){r,e:=c.DB.ExecContext(ctx,`INSERT OR IGNORE INTO workset_keys(namespace,key) VALUES(?,?)`,ns,key);if e!=nil{return false,e};n,_:=r.RowsAffected();return n==1,nil}
func(c *ClientStore)Walk(ctx context.Context,ns string,fn func(string)error)error{rows,e:=c.DB.QueryContext(ctx,`SELECT key FROM workset_keys WHERE namespace=? ORDER BY key`,ns);if e!=nil{return e};defer rows.Close();for rows.Next(){var k string;if e=rows.Scan(&k);e!=nil{return e};if e=fn(k);e!=nil{return e}};return rows.Err()}
func(c *ClientStore)StoreCapsule(ctx context.Context,cap domain.StateCapsule,path string,cats map[string]string)error{b,e:=json.Marshal(cap);if e!=nil{return e};tx,e:=c.DB.BeginTx(ctx,nil);if e!=nil{return e};defer tx.Rollback();if _,e=tx.ExecContext(ctx,`INSERT INTO state_capsules(id,file_path,exported_at,imported_at,state_json) VALUES(?,?,?,?,?)`,cap.ID,path,tstr(cap.ExportedAt),tstr(time.Now()),b);e!=nil{return e};for _,x:=range cap.Catalogs{if _,e=tx.ExecContext(ctx,`INSERT INTO capsule_catalogs(capsule_id,source_id,file_path,sha256,size) VALUES(?,?,?,?,?)`,cap.ID,x.SourceID,cats[x.SourceID],x.SHA256,x.Size);e!=nil{return e}};return tx.Commit()}
