package sqlite

import("context";"database/sql";"encoding/json";"errors";"fmt";"time";"github.com/ynw0/airgap-mirror/internal/domain")
type ServerStore struct{DB *sql.DB}; func NewServerStore(db *sql.DB)*ServerStore{return &ServerStore{DB:db}}
func tstr(t time.Time)string{return t.UTC().Format(time.RFC3339Nano)};func ptime(s sql.NullString)*time.Time{if !s.Valid{return nil};t,e:=time.Parse(time.RFC3339Nano,s.String);if e!=nil{return nil};return &t};func asNotFound(e error)error{if errors.Is(e,sql.ErrNoRows){return domain.ErrNotFound};return e}
func(s *ServerStore)Create(ctx context.Context,v domain.Source)error{_,e:=s.DB.ExecContext(ctx,`INSERT INTO sources(id,name,type,provider,upstream_url,root_path,public_url,enabled,config_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,v.ID,v.Name,v.Type,v.Provider,v.UpstreamURL,v.RootPath,v.PublicURL,v.Enabled,[]byte(v.ConfigJSON),tstr(v.CreatedAt),tstr(v.UpdatedAt));return e}
func(s *ServerStore)Update(ctx context.Context,v domain.Source)error{r,e:=s.DB.ExecContext(ctx,`UPDATE sources SET name=?,type=?,provider=?,upstream_url=?,root_path=?,public_url=?,enabled=?,config_json=?,updated_at=? WHERE id=?`,v.Name,v.Type,v.Provider,v.UpstreamURL,v.RootPath,v.PublicURL,v.Enabled,[]byte(v.ConfigJSON),tstr(v.UpdatedAt),v.ID);if e!=nil{return e};n,_:=r.RowsAffected();if n==0{return domain.ErrNotFound};return nil}
func(s *ServerStore)Get(ctx context.Context,id string)(domain.Source,error){var v domain.Source;var typ string;var cfg []byte;var ca,ua string;e:=s.DB.QueryRowContext(ctx,`SELECT id,name,type,provider,upstream_url,root_path,public_url,enabled,config_json,created_at,updated_at FROM sources WHERE id=?`,id).Scan(&v.ID,&v.Name,&typ,&v.Provider,&v.UpstreamURL,&v.RootPath,&v.PublicURL,&v.Enabled,&cfg,&ca,&ua);if e!=nil{return v,asNotFound(e)};v.Type=domain.SourceType(typ);v.ConfigJSON=cfg;v.CreatedAt,_=time.Parse(time.RFC3339Nano,ca);v.UpdatedAt,_=time.Parse(time.RFC3339Nano,ua);return v,nil}
func(s *ServerStore)List(ctx context.Context)([]domain.Source,error){rows,e:=s.DB.QueryContext(ctx,`SELECT id FROM sources ORDER BY name,id`);if e!=nil{return nil,e};defer rows.Close();var out []domain.Source;for rows.Next(){var id string;if e=rows.Scan(&id);e!=nil{return nil,e};v,e:=s.Get(ctx,id);if e!=nil{return nil,e};out=append(out,v)};return out,rows.Err()}
func(s *ServerStore)GetState(ctx context.Context,id string)(domain.SourceState,error){var v domain.SourceState;var k,val,at string;var active sql.NullString;e:=s.DB.QueryRowContext(ctx,`SELECT source_id,cursor_kind,cursor_value,catalog_version,live_bytes,live_objects,active_epoch_id,updated_at FROM source_states WHERE source_id=?`,id).Scan(&v.SourceID,&k,&val,&v.CatalogVersion,&v.LiveBytes,&v.LiveObjects,&active,&at);if e!=nil{return v,asNotFound(e)};v.LiveCursor=domain.Cursor{Kind:k,Value:val};if active.Valid{v.ActiveEpochID=active.String};v.UpdatedAt,_=time.Parse(time.RFC3339Nano,at);return v,nil}
func(s *ServerStore)PutState(ctx context.Context,v domain.SourceState)error{_,e:=s.DB.ExecContext(ctx,`INSERT INTO source_states(source_id,cursor_kind,cursor_value,catalog_version,live_bytes,live_objects,active_epoch_id,updated_at) VALUES(?,?,?,?,?,?,NULLIF(?,''),?) ON CONFLICT(source_id) DO UPDATE SET cursor_kind=excluded.cursor_kind,cursor_value=excluded.cursor_value,catalog_version=excluded.catalog_version,live_bytes=excluded.live_bytes,live_objects=excluded.live_objects,active_epoch_id=excluded.active_epoch_id,updated_at=excluded.updated_at`,v.SourceID,v.LiveCursor.Kind,v.LiveCursor.Value,v.CatalogVersion,v.LiveBytes,v.LiveObjects,v.ActiveEpochID,tstr(v.UpdatedAt));return e}
func(s *ServerStore)CreateEpoch(ctx context.Context,v domain.Epoch)error{_,e:=s.DB.ExecContext(ctx,`INSERT INTO epochs(id,source_id,base_cursor_kind,base_cursor_value,target_cursor_kind,target_cursor_value,status,total_bytes,total_objects,total_batches,publish_unit_count,created_at,error_text) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,v.ID,v.SourceID,v.BaseCursor.Kind,v.BaseCursor.Value,v.TargetCursor.Kind,v.TargetCursor.Value,v.Status,v.TotalBytes,v.TotalObjects,v.TotalBatches,v.PublishUnitCount,tstr(v.CreatedAt),v.ErrorText);return e}
func(s *ServerStore)GetEpoch(ctx context.Context,id string)(domain.Epoch,error){var v domain.Epoch;var bk,bv,tk,tv,created string;var done sql.NullString;e:=s.DB.QueryRowContext(ctx,`SELECT id,source_id,base_cursor_kind,base_cursor_value,target_cursor_kind,target_cursor_value,status,total_bytes,total_objects,total_batches,publish_unit_count,created_at,completed_at,error_text FROM epochs WHERE id=?`,id).Scan(&v.ID,&v.SourceID,&bk,&bv,&tk,&tv,&v.Status,&v.TotalBytes,&v.TotalObjects,&v.TotalBatches,&v.PublishUnitCount,&created,&done,&v.ErrorText);if e!=nil{return v,asNotFound(e)};v.BaseCursor=domain.Cursor{Kind:bk,Value:bv};v.TargetCursor=domain.Cursor{Kind:tk,Value:tv};v.CreatedAt,_=time.Parse(time.RFC3339Nano,created);v.CompletedAt=ptime(done);return v,nil}
func(s *ServerStore)TransitionEpoch(ctx context.Context,id string,to domain.EpochStatus,msg string)error{v,e:=s.GetEpoch(ctx,id);if e!=nil{return e};if e=domain.ValidateEpochTransition(v.Status,to);e!=nil{return e};_,e=s.DB.ExecContext(ctx,`UPDATE epochs SET status=?,error_text=? WHERE id=?`,to,msg,id);return e}
func(s *ServerStore)CreateBatch(ctx context.Context,v domain.Batch)error{_,e:=s.DB.ExecContext(ctx,`INSERT INTO batches(id,epoch_id,source_id,sequence,status,planned_bytes,object_count,pack_count,created_at,error_text) VALUES(?,?,?,?,?,?,?,?,?,?)`,v.ID,v.EpochID,v.SourceID,v.Sequence,v.Status,v.PlannedBytes,v.ObjectCount,v.PackCount,tstr(v.CreatedAt),v.ErrorText);return e}
func(s *ServerStore)GetBatch(ctx context.Context,id string)(domain.Batch,error){var v domain.Batch;var created string;var imp sql.NullString;e:=s.DB.QueryRowContext(ctx,`SELECT id,epoch_id,source_id,sequence,status,planned_bytes,object_count,pack_count,created_at,imported_at,error_text FROM batches WHERE id=?`,id).Scan(&v.ID,&v.EpochID,&v.SourceID,&v.Sequence,&v.Status,&v.PlannedBytes,&v.ObjectCount,&v.PackCount,&created,&imp,&v.ErrorText);if e!=nil{return v,asNotFound(e)};v.CreatedAt,_=time.Parse(time.RFC3339Nano,created);v.ImportedAt=ptime(imp);return v,nil}
func(s *ServerStore)TransitionBatch(ctx context.Context,id string,to domain.BatchStatus,msg string)error{v,e:=s.GetBatch(ctx,id);if e!=nil{return e};if e=domain.ValidateBatchTransition(v.Status,to);e!=nil{return e};_,e=s.DB.ExecContext(ctx,`UPDATE batches SET status=?,error_text=? WHERE id=?`,to,msg,id);return e}
func(s *ServerStore)DeclarePublishUnit(ctx context.Context,u domain.PublishUnit)error{tx,e:=s.DB.BeginTx(ctx,nil);if e!=nil{return e};defer tx.Rollback();var eid,sid,key string;var req int64;e=tx.QueryRowContext(ctx,`SELECT epoch_id,source_id,unit_key,required_count FROM publish_units WHERE id=?`,u.ID).Scan(&eid,&sid,&key,&req);if e==nil{if eid!=u.EpochID||sid!=u.SourceID||key!=u.Key||req!=u.Required{return fmt.Errorf("publish unit declaration mismatch: %w",domain.ErrConflict)};return tx.Commit()};if !errors.Is(e,sql.ErrNoRows){return e};_,e=tx.ExecContext(ctx,`INSERT INTO publish_units(id,epoch_id,source_id,unit_key,status,required_count,imported_count,metadata_path) VALUES(?,?,?,?,?,?,0,?)`,u.ID,u.EpochID,u.SourceID,u.Key,domain.PublishWaiting,u.Required,u.MetadataPath);if e!=nil{return e};return tx.Commit()}
func(s *ServerStore)GetCatalog(ctx context.Context,sid,path string)(domain.CatalogEntry,error){var v domain.CatalogEntry;var a []byte;var at string;e:=s.DB.QueryRowContext(ctx,`SELECT source_id,logical_path,size,sha256,package_key,version,attributes,updated_at FROM catalog_entries WHERE source_id=? AND logical_path=?`,sid,path).Scan(&v.SourceID,&v.LogicalPath,&v.Size,&v.SHA256,&v.PackageKey,&v.Version,&a,&at);if e!=nil{return v,asNotFound(e)};v.Attributes=a;v.UpdatedAt,_=time.Parse(time.RFC3339Nano,at);return v,nil}
func(s *ServerStore)UpsertCatalog(ctx context.Context,v domain.CatalogEntry)error{_,e:=s.DB.ExecContext(ctx,`INSERT INTO catalog_entries(source_id,logical_path,size,sha256,package_key,version,attributes,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(source_id,logical_path) DO UPDATE SET size=excluded.size,sha256=excluded.sha256,package_key=excluded.package_key,version=excluded.version,attributes=excluded.attributes,updated_at=excluded.updated_at`,v.SourceID,v.LogicalPath,v.Size,v.SHA256,v.PackageKey,v.Version,[]byte(v.Attributes),tstr(v.UpdatedAt));return e}
func(s *ServerStore)CatalogStats(ctx context.Context,sid string)(domain.CatalogStats,error){v:=domain.CatalogStats{SourceID:sid};e:=s.DB.QueryRowContext(ctx,`SELECT COALESCE(SUM(size),0),COUNT(*) FROM catalog_entries WHERE source_id=?`,sid).Scan(&v.Bytes,&v.Objects);return v,e}
func(s *ServerStore)Audit(ctx context.Context,e domain.AuditEvent)error{d:=[]byte(e.Detail);if d==nil{d,_=json.Marshal(map[string]any{})};_,err:=s.DB.ExecContext(ctx,`INSERT INTO audit_logs(id,kind,source_id,epoch_id,batch_id,message,detail,created_at) VALUES(?,?,?,?,?,?,?,?)`,e.ID,e.Kind,e.SourceID,e.EpochID,e.BatchID,e.Message,d,tstr(e.CreatedAt));return err}
